// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp06Store.ShopUI.Models;

#nullable disable

namespace asp06Store.ShopUI.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("asp06Store.ShopUI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Description = "sumsumng 1 best mobile for this price",
                            Name = "sumsumng 1",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Description = " sumsumng 2 best mobile for this price",
                            Name = "sumsumng 2",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 3,
                            Category = "Mobile",
                            Description = " IPhone 2 best mobile for this price",
                            Name = "IPhone 3",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mobile",
                            Description = " IPhone 4 best mobile for this price",
                            Name = "IPhone 4",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mobile",
                            Description = " IPhone 5 best mobile for this price",
                            Name = "Xiomi 5",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 6,
                            Category = "Loptop",
                            Description = "sumsumng 1 best mobile for this price",
                            Name = "asus 6",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 7,
                            Category = "Loptop",
                            Description = " sumsumng 2 best mobile for this price",
                            Name = "hp 7",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 8,
                            Category = "Loptop",
                            Description = " IPhone 2 best mobile for this price",
                            Name = "vivo 8",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 9,
                            Category = "Loptop",
                            Description = " IPhone 4 best mobile for this price",
                            Name = "asus 9",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 10,
                            Category = "Loptop",
                            Description = " IPhone 5 best mobile for this price",
                            Name = "Xiomi 10",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 11,
                            Category = "Pc",
                            Description = " sumsumng 2 best mobile for this price",
                            Name = "pc 11",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pc",
                            Description = " IPhone 2 best mobile for this price",
                            Name = "vivo 12",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pc",
                            Description = " IPhone 4 best mobile for this price",
                            Name = "asus 13",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 14,
                            Category = "Pc",
                            Description = " IPhone 4 best mobile for this price",
                            Name = "asus 14",
                            Price = 30000000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
